routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('email-test', function(){
	$quote = 'yo@gmail.com';


    dispatch(new App\Jobs\SendEmailRequestQuoteJob());


    dd('done');
});
Route::get('email', 'HomeController@sendEmail');

Route::get('send', 'Backend\EmailController@sendingEmail');

Route::get('show-package-img', 'Frontend\WebhookController@showPackageImg');

Route::get('faq', 'Frontend\FaqController@index');

Route::group(['prefix' => 'backend-order','middleware' => ['auth']], function()
{
	Route::resource('order','Backend\OrderController');
});

Route::group(['prefix' => 'frontend'], function()
{
	Route::get('package/{id}','Frontend\PackageController@show');	
});
Route::get('/',function(){
	return view('home');
});
Route::get('lang/{locale}', 'HomeController@lang');


Route::group(['prefix' => 'backend','middleware' => ['auth','permission:menu-access']], function()
{
    Route::get('user', 'AuthController@user');
	Route::post('package-image-upload/{id}','Backend\PackageController@packageImageUpload')->name('package_image.store');
	Route::delete('package-image-upload/{packageid}/{fileid}', [
    'as' => 'destroy', 
    'uses' => 'Backend\PackageController@packageImageDestroy'
	]);	
	Route::delete('approve-invoice-img-destroy/{orderid}/{fileid}', [
    'as' => 'invoice_img_destroy', 
    'uses' => 'Backend\OrderController@approveInvoiceImgDestroy'
	]);
	Route::resource('customer','Backend\CustomerController');
	Route::resource('exchange-rate','Backend\ExchangeRateController');
	Route::resource('operator','Backend\OperatorController');
	Route::resource('quote','Backend\QuoteController');
	Route::resource('faq','Backend\FaqController');
	Route::resource('package','Backend\PackageController');
	Route::resource('destination','Backend\DestinationController');
    Route::resource('roles','Backend\RoleController');
    Route::resource('users','Backend\UserController');
    Route::resource('currency','Backend\CurrencyController');
    Route::put('/orderapprove/{orderid}','Backend\OrderController@orderApprove')->name('order.approve');
	//order from messenger bot
	Route::get('check-available-package/{id}','Backend\PackageController@checkPackage');
	Route::get('approve-invoice-img/{id}','Backend\OrderController@approveInvoiceImg')->name('order.approveInvoiceImg');	
	Route::post('approve-invoice-img-store/{id}','Backend\OrderController@approveInvoiceImgStore')->name('approveInvoiceImg.store');
	Route::get('check-available-package-list','Backend\PackageController@checkPackageList');
	Route::put('check-available-package/{id}','Backend\PackageController@packageInquiryUpdate')->name('check-package.update');
});

// Login
// Authentication Routes...
$this->get('admin/btny', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/btny', 'Auth\LoginController@login');
$this->post('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('admin/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('admin/register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
 $this->post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('admin/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('admin/password/reset', 'Auth\ResetPasswordController@reset');

app/Http/Controllers/Backend/APIController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client; 

class APIController extends Controller
{
  public function sendWelcomeChatBlock($messenger_user_id,$is_welcome)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5b7c52fa0ecd9f7e970399c0';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&is_welcome='.$is_welcome;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }      
  public function sendEmptyPackage($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5d305a48f4bfde00010cc1ba';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    
  public function sendRequestLiveChatBlock($messenger_user_id,$is_live_chat)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5ccd4698cd9d1800066f167b';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&is_live_chat='.$is_live_chat;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }  
  public function sendThankyouRatigInfo($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5cb96a134b7d020006eee7e6';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }  
  public function sendRatePackageBlock($messenger_user_id,$package_id,$package_name,$order_id,$tour_leader_name)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c69546f76ccbc29ae3c72fb';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&package_id='.$package_id.'&package_name='.$package_name.'&order_id='.$order_id.'&tour_leader_name='.$tour_leader_name;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }  
  public function sendDepositWaitingMessage($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c5a621176ccbc6c2a75036e';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }     
  public function sendBookingSaveBlock($messenger_user_id,$booking_code,$order_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c59632a0ecd9f5655b29481';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&booking_code='.$booking_code.'&order_id='.$order_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }     
  public function sendapproveInvoiceImgBlock($messenger_user_id,$order_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c5957890ecd9f5655a70ba5';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&order_id='.$order_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    
  public function sendOrderCancelBlock($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c5867a90ecd9f5655d71eab';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    

  public function sendCheckAvailableFailBlock($messenger_user_id,$package_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c3cb9f476ccbc01c2a11e4d';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&package_id='.$package_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }     
  public function sendOrderInquiryFail($messenger_user_id,$package_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c3cb0dc76ccbc01c2951af8';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&package_id='.$package_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }   
  public function sendWaitingMessage($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c31d85a0ecd9f2f91ff5702';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    
  public function sendInfoPaymentBlock($messenger_user_id,$bank_info,$deposit_amt,$exchange_rate,$payment_deadline,$quantity)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c3b42eb76ccbc01c2a8ab79';

app/Http/Controllers/Backend/CurrencyController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Currency;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
    {
       $currency = Currency::paginate(10);
       return view('backend.currency.index',compact('currency')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         // return view("backend.currency.index");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $currency = new Currency();
        // $currency->denomination = Input::get('denomination');


        // if($currency->save())
        // {
        //     Session::flash('message','Currency was successfully created');
        //     Session::flash('m-class','alert-success');
        //     return back()->with('success','Currency successfully added!');
        // }
        // else
        // {
        //     Session::flash('message','Data is not saved');
        //     Session::flash('m-class','alert-danger');
        //     return redirect('backend');
        // }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function show(Township $township)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        // $currency = Currency::findOrFail($id);
       
        // return view("backend.currency.edit", compact('currency'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $currency = Currency::find($id);

        // $currency->denomination = Input::get('denomination');

        // if($currency->save())
        // {
        //     Session::flash('message','Currency was successfully updated');
        //     Session::flash('m-class','alert-success');
        //     return redirect('backend/currency')->with('success','Currency successfully updated!');
        // }
        // else
        // {
        //     Session::flash('message','Data is not saved');
        //     Session::flash('m-class','alert-danger');
        //     return redirect('backend');
        // }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
    //     $currency->delete();
    //     return redirect()->route('currency.index')
    //                     ->with('success','Currency deleted successfully');
    
    }
}

app/Http/Controllers/Backend/QuoteController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{Quote};
class QuoteController extends Controller
{

    public function index(Request $request)
    {   
  		// if(count($request->all())!=0){  
    //         $quotes = Quote::Search($request)->paginate(10);      
    //     }
    //     else{
        $quotes = Quote::paginate(12);
        // }  

        return view("backend.quote.index",compact('quotes'));
    }

}

resources/views/backend/order/approve_invoice_img.blade.php
@extends('layouts.default')

@section('content')
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.0.1/min/dropzone.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.2.0/min/dropzone.min.js"></script>

<h2>Upload Invoice Image</h2>
<div class="container">
<div class="row">
    <div class="list-group">
        @foreach($order->getMedia('approve_invoice_img') as $file)
        <div class="list-group-item">
            <div class="media">
                <div class="media-left">
                    @if(starts_with($file->mime_type, 'image'))
                        <a href="{{ $file->getUrl() }}" target="_blank">
                            <img class="media-object" src="{{ $file->getUrl() }}" alt="{{ $file->name }}" width="200px">
                        </a>
                    @else
                        <span class="glyphicon glyphicon-file large-icon"></span>
                    @endif
                </div>
                <div class="media-body">
                    <div class="btn-group pull-right">
                        <form action="{{ route('invoice_img_destroy',[$order->order_id,$file->id]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                        </form>
                    </div>
                    <h4 class="media-heading">{{ $file->name }}</h4>
                    <p> 
                        <small>
                            {{ $file->human_readable_size }} |
                            {{ $file->mime_type }}
                        </small>
                    </p>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
    <form action="{{ route('approveInvoiceImg.store', $order->order_id) }}" method="POST" enctype="multipart/form-data"> 
            {{ csrf_field() }}
        <div class="form-group"> 
          <input type="file" name="image" id="image">
        </div>
        <div class="form-group"> 
          <button type="submit" class="btn btn-success">Send</button>
        </div>
    </form>
</div>

<script type="text/javascript">
  Dropzone.options.mediaDropzone = {
    parallelUploads: 1,
    init: function () {
        this.on("queuecomplete", function (file) {
            location.reload();
        });
    }
};
</script>
@endsection

resources/views/backend/order/edit.blade.php
@extends('layouts.default')

@section('content')
<h2>Edit Order info</h2>
 
  <div class="col-md-6">
	<form action="{{ route('order.update', $order->order_id) }}" enctype="multipart/form-data" method="POST">
      {{ csrf_field() }}
     
            <div class="form-group">
              {!! Form::label('Name') !!}
              {!! Form::text('name', $order->customer->name, array('required','class'=>'form-control', 
              'placeholder'=>' Name')) !!}
            </div>
            <div class="form-group">
              {!! Form::label('Phone') !!}
              {!! Form::text('ph_num', $order->customer->ph_num, array('required','class'=>'form-control', 
              'placeholder'=>' Phone')) !!}
            </div>            

            <div class="form-group">
              {!! Form::label('Quantity') !!}
              {!! Form::text('quantity', $order->quantity, array('required','class'=>'form-control', 
              'placeholder'=>' Phone')) !!}
            </div>
                         
            <div class="form-group">
              {!! Form::label('Price') !!}
              {!! Form::text('price_each', $order->price_each, array('required','class'=>'form-control', 
              'placeholder'=>' Phone')) !!}
            </div>
             
             <div class="form-group">
                {!! Form::label('Email') !!}
                {!! Form::text('email', $order->customer->email, array('required','class'=>'form-control', 
                'placeholder'=>' Email')) !!}
              </div>
              <select name="status">
                <option value="{!! $order->status !!}">{!! $order->status !!}</option>
                <option value="fully-paid">Fully Paid</option>
                <option value="deposited">Deposited</option>
                <option value="waiting-for-receipt">Waiting for receipt</option>
                
              </select>
              
              <div class="form-group"> 
              <form action="{{ route('order.update', $order->order_id) }}">
                 {{ csrf_field() }}
                 {{ method_field("patch") }}
              <button type="submit" class="btn btn-primary">Update Info</button>
              </form>
      </div> 
      </div>
    </form>

@endsection

resources/views/backend/order/index.blade.php
@extends('layouts.default')

@section('content')

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Orders</h1>
    </div>
</div>
 <div class="table-responsive">
 
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Order Id</th>
            <th>Booking Code</th>
            <th>Name</th>
            <th>Facebook Name</th>
            <th>Ph Number</th>
            <th>Email</th>
            <th>Quantity</th>
            <th>Package Name</th>
            <th>Price Each</th>
            <th>Deposit Amount</th>
            <th>Passport Image</th>
            <th>Slip Image</th>
            <th>Created at</th>
            <th>Payment Deadline</th>
            <th>Status</th>
            <th>Payment Type</th>
            <th>Approve Invoice</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
    @foreach($orders as $row )
        <tr>
        @if(Gate::allows('view-ownorder', $row)) 
     
            <td>{{$row->order_id}}</td>
            <td>{{$row->booking_code}}</td>
            <td> {{$row->name}}</td>
            <td>@if($row->customer) {{$row->customer->first_name}} {{$row->customer->last_name}} @endif</td>
            <td>{{$row->ph_num}} </td>
            <td> {{$row->email}} </td>
            <td>{{$row->quantity}}</td>
            <td>@if($row->package){{$row->package->name}} @endif</td>
            <td>{{$row->price_each}}</td>
            <td>{{$row->deposit_amt}}</td>
            <td><img src="{{$row->passport_img}}" width="100px"></td>
            <td><img src="{{$row->upload_slip}}" width="100px"></td>
            <td>{{ Carbon\Carbon::parse($row->created_at)->format('Y-m-d')}}</td>
            <td>{{ Carbon\Carbon::parse($row->payment_deadline)->format('Y-m-d')}}</td>
            <td>{{$row->status}}</td>
            <td>{{$row->payment_type}}</td>
            <td>
                <a href="{{ route('order.approveInvoiceImg', $row->order_id) }}" class="btn btn-warning btn-xs action-item" target="_blank"><i class="glyphicon glyphicon-edit"></i></a>
            </td>
            <td>
            @if(Gate::allows('update-order', $row)) 
                <a href="{{ route('order.edit', $row->order_id) }}" class="btn btn-warning btn-xs action-item" target="_blank"><i class="glyphicon glyphicon-edit"></i></a>
            @endif
            </td>
            <td>
            @if(Gate::allows('delete-order', $row)) 
                <form action="{{ route('order.destroy',$row->order_id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-xs ">Delete</button>
                </form>
            @endif
            </td>
        @endif
        </tr>
    @endforeach  
    </tbody>
</table>
  {{ $orders->links() }}
</div>
@endsection

resources/views/backend/order/show.blade.php
@extends('layouts.default')



@section('content')

<div class="row">

    <div class="col-lg-12">

        <h1 class="page-header">Order Detail</h1>

    </div>
</div>

<table class="table table-striped table-bordered table-hover">

    <thead>
        <tr>
            <th>#</th>
            <th>Order Id</th>
            <th>Name</th>
            <th>Messenger User Id</th>
            <th>Chatfuel User Id</th>
            <th>Ph Number</th>
            <th>Email</th>
            <th>Quantity</th>
            <th>Price Each</th>
            <th>Approval</th>
            <th>Approve</th>
            <th>Unapprove</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{$order->id}}</td>
            <td>{{$order->order_id}}</td>
            <td>{{$order->name}}</td>
            <td>{{$order->messenger_user_id}}</td>
            <td>{{$order->chatfuel_user_id}}</td>
            <td>{{$order->ph_num}}</td>
            <td>{{$order->email}}</td>
            <td>{{$order->quantity}}</td>
            <td>{{$order->price_each}}</td>
            <td>@if ($order->approval == 1)
                <div class="text-success"> Approved</div>
                @else
                <div class="text-danger">Unapproved</div>
                @endif   
            </td>
             <td>
              <form action="{{ route('order.approve',$order->order_id) }}" method="POST">
                @csrf
                @method('PUT')
               <input class="hide" type="checkbox" name="approval" value="1" checked> 
               <button type="submit" class="btn btn-success">Approve</button>
               </form>
            </td>

            <td>
              <form action="{{ route('order.approve',$order->order_id) }}" method="POST">
                    @csrf
                    @method('PUT')
               <input type="checkbox"  class="hide" name="approval" value="0" checked> 
               <button type="submit" class="btn btn-danger">Unapprove</button>
               </form>
            </td>
        </tr>     
    </tbody>
</table>

@endsection