routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('email-test', function(){
	$quote = 'yo@gmail.com';


    dispatch(new App\Jobs\SendEmailRequestQuoteJob());


    dd('done');
});
Route::get('email', 'HomeController@sendEmail');

Route::get('send', 'Backend\EmailController@sendingEmail');

Route::get('show-package-img', 'Frontend\WebhookController@showPackageImg');

Route::get('faq', 'Frontend\FaqController@index');

Route::group(['prefix' => 'backend-order','middleware' => ['auth']], function()
{
	Route::resource('order','Backend\OrderController');
});

Route::group(['prefix' => 'frontend'], function()
{
	Route::get('package/{id}','Frontend\PackageController@show');	
});
Route::get('/',function(){
	return view('home');
});
Route::get('lang/{locale}', 'HomeController@lang');


Route::group(['prefix' => 'backend','middleware' => ['auth','permission:menu-access']], function()
{
    Route::get('user', 'AuthController@user');
	Route::post('package-image-upload/{id}','Backend\PackageController@packageImageUpload')->name('package_image.store');
	Route::delete('package-image-upload/{packageid}/{fileid}', [
    'as' => 'destroy', 
    'uses' => 'Backend\PackageController@packageImageDestroy'
	]);	
	Route::delete('approve-invoice-img-destroy/{orderid}/{fileid}', [
    'as' => 'invoice_img_destroy', 
    'uses' => 'Backend\OrderController@approveInvoiceImgDestroy'
	]);
	Route::resource('customer','Backend\CustomerController');
	Route::resource('exchange-rate','Backend\ExchangeRateController');
	Route::resource('operator','Backend\OperatorController');
	Route::resource('quote','Backend\QuoteController');
	Route::resource('faq','Backend\FaqController');
	Route::resource('package','Backend\PackageController');
	Route::resource('destination','Backend\DestinationController');
    Route::resource('roles','Backend\RoleController');
    Route::resource('users','Backend\UserController');
    Route::resource('currency','Backend\CurrencyController');
    Route::put('/orderapprove/{orderid}','Backend\OrderController@orderApprove')->name('order.approve');
	//order from messenger bot
	Route::get('check-available-package/{id}','Backend\PackageController@checkPackage');
	Route::get('approve-invoice-img/{id}','Backend\OrderController@approveInvoiceImg')->name('order.approveInvoiceImg');	
	Route::post('approve-invoice-img-store/{id}','Backend\OrderController@approveInvoiceImgStore')->name('approveInvoiceImg.store');
	Route::get('check-available-package-list','Backend\PackageController@checkPackageList');
	Route::put('check-available-package/{id}','Backend\PackageController@packageInquiryUpdate')->name('check-package.update');
});

// Login
// Authentication Routes...
$this->get('admin/btny', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/btny', 'Auth\LoginController@login');
$this->post('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('admin/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('admin/register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
 $this->post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('admin/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('admin/password/reset', 'Auth\ResetPasswordController@reset');

app/Http/Controllers/Backend/APIController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client; 

class APIController extends Controller
{
  public function sendWelcomeChatBlock($messenger_user_id,$is_welcome)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5b7c52fa0ecd9f7e970399c0';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&is_welcome='.$is_welcome;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }      
  public function sendEmptyPackage($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5d305a48f4bfde00010cc1ba';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    
  public function sendRequestLiveChatBlock($messenger_user_id,$is_live_chat)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5ccd4698cd9d1800066f167b';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&is_live_chat='.$is_live_chat;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }  
  public function sendThankyouRatigInfo($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5cb96a134b7d020006eee7e6';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }  
  public function sendRatePackageBlock($messenger_user_id,$package_id,$package_name,$order_id,$tour_leader_name)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c69546f76ccbc29ae3c72fb';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&package_id='.$package_id.'&package_name='.$package_name.'&order_id='.$order_id.'&tour_leader_name='.$tour_leader_name;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }  
  public function sendDepositWaitingMessage($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c5a621176ccbc6c2a75036e';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }     
  public function sendBookingSaveBlock($messenger_user_id,$booking_code,$order_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c59632a0ecd9f5655b29481';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&booking_code='.$booking_code.'&order_id='.$order_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }     
  public function sendapproveInvoiceImgBlock($messenger_user_id,$order_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c5957890ecd9f5655a70ba5';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&order_id='.$order_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    
  public function sendOrderCancelBlock($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c5867a90ecd9f5655d71eab';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    

  public function sendCheckAvailableFailBlock($messenger_user_id,$package_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c3cb9f476ccbc01c2a11e4d';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&package_id='.$package_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }     
  public function sendOrderInquiryFail($messenger_user_id,$package_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c3cb0dc76ccbc01c2951af8';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block.'&package_id='.$package_id;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }   
  public function sendWaitingMessage($messenger_user_id)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c31d85a0ecd9f2f91ff5702';
    $url = 'https://api.chatfuel.com/bots/'.$bot_id.'/users/'.$user_id.'/send?chatfuel_token='.$token.'&chatfuel_message_tag=APPLICATION_UPDATE&chatfuel_block_id='.$block;

    $client = new Client;   
        try {
            $response = $client->post($url);
            return json_decode( $response->getBody()->getContents(),true );
        } catch (ClientException $e) {
          return json_decode( $e->getResponse()->getBody()->getContents(),true );
        }  
  }    
  public function sendInfoPaymentBlock($messenger_user_id,$bank_info,$deposit_amt,$exchange_rate,$payment_deadline,$quantity)
  {
    $bot_id = '5b7c52fa0ecd9f7e970399b1';
    $user_id = $messenger_user_id;
    $token = 'mELtlMAHYqR0BvgEiMq8zVek3uYUK3OJMbtyrdNPTrQB9ndV0fM7lWTFZbM4MZvD';
    $block = '5c3b42eb76ccbc01c2a8ab79';

app/Http/Controllers/Backend/CurrencyController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Currency;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
    {
       $currency = Currency::paginate(10);
       return view('backend.currency.index',compact('currency')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         // return view("backend.currency.index");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $currency = new Currency();
        // $currency->denomination = Input::get('denomination');


        // if($currency->save())
        // {
        //     Session::flash('message','Currency was successfully created');
        //     Session::flash('m-class','alert-success');
        //     return back()->with('success','Currency successfully added!');
        // }
        // else
        // {
        //     Session::flash('message','Data is not saved');
        //     Session::flash('m-class','alert-danger');
        //     return redirect('backend');
        // }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function show(Township $township)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        // $currency = Currency::findOrFail($id);
       
        // return view("backend.currency.edit", compact('currency'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $currency = Currency::find($id);

        // $currency->denomination = Input::get('denomination');

        // if($currency->save())
        // {
        //     Session::flash('message','Currency was successfully updated');
        //     Session::flash('m-class','alert-success');
        //     return redirect('backend/currency')->with('success','Currency successfully updated!');
        // }
        // else
        // {
        //     Session::flash('message','Data is not saved');
        //     Session::flash('m-class','alert-danger');
        //     return redirect('backend');
        // }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Township  $township
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
    //     $currency->delete();
    //     return redirect()->route('currency.index')
    //                     ->with('success','Currency deleted successfully');
    
    }
}

app/Http/Controllers/Backend/QuoteController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{Quote};
class QuoteController extends Controller
{

    public function index(Request $request)
    {   
  		// if(count($request->all())!=0){  
    //         $quotes = Quote::Search($request)->paginate(10);      
    //     }
    //     else{
        $quotes = Quote::paginate(12);
        // }  

        return view("backend.quote.index",compact('quotes'));
    }

}

resources/views/backend/destination/create.blade.php
@extends('layouts.default')
@section('content')

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Destination Create Form</h1>
    </div>
</div>

<form action="{{ route('destination.store') }}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}
      
          <div class="form-group">
            {!! Form::label('Eng Name') !!}
            {!! Form::text('name', null, array('required','class'=>'form-control', 
            'placeholder'=>' Name')) !!}
          </div>          

          <div class="form-group">
            {!! Form::label('Zawgyi Name') !!}
            {!! Form::text('zg_name', null, array('required','class'=>'form-control', 
            'placeholder'=>' Name')) !!}
          </div>          


          <div class="form-group"> 
            <button type="submit" class="btn btn-success">Create Destination</button>
          </div>
</form>
    
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
    CKEDITOR.replace( 'descriptions' );
    // var x = document.getElementById("myTextarea").required;

    </script>
@endsection

resources/views/backend/destination/edit.blade.php
@extends('layouts.default')
@section('content')
<style type="text/css">
  .update-img{
    display: none;
  }
  .img-update{
        background: #ebb940;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    color: #212121;
    font-family: Montserrat-Bold,"Arial",sans-serif;
    /* font-size: 13px; */
    display: inline-block;
    padding: 9px 14px;
  }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(".img-update").on("click", function(){
       $('.update-img').css('display','block');
    });
});
</script>
<h2>Edit Destination info</h2>
 
  <div class="col-md-6">
	<form action="{{ route('destination.update', $destination->id) }}" enctype="multipart/form-data" method="POST">
      {{ csrf_field() }}
     
            <div class="form-group">
              {!! Form::label('Name') !!}
              {!! Form::text('name', $destination->name, array('required','class'=>'form-control', 
              'placeholder'=>' Name')) !!}
            </div>                        
            <div class="form-group">
              {!! Form::label('Zg Name') !!}
              {!! Form::text('zg_name', $destination->translate('zg')['name'], array('required','class'=>'form-control', 
              'placeholder'=>'Zg Name')) !!}
            </div>            

         

            <div class="form-group"> 
            <form action="{{ route('destination.update', $destination->id) }}">
               {{ csrf_field() }}
               {{ method_field("patch") }}
                <button type="submit" class="btn btn-primary">Update Info</button>
            </form>

      </div> 
      </div>
    </form>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script>
CKEDITOR.replace( 'descriptions' );
</script>
@endsection

resources/views/backend/destination/index.blade.php
    @extends('layouts.default')

    @section('content')

    <div class="row">

        <div class="col-lg-12">

            <h1 class="page-header">Destinations</h1>

        </div>

    </div>

<div class="create">
<button class="btn btn-success"><a href="{{route('destination.create')}}">Create</a></button>
</div>
<br>

<div class="row">
 
        {!! Form::open(['url'=>route('destination.index'),'method'=>'GET', 'class'=>'form', 'id'=>'search_data']) !!}

            <div class="form-group col-md-4"> 
                <input type="text" name="destination_name" placeholder="Name" value="{{request()->input('destination_name')}}" class="form-control"/>
            </div>
                       
            <div class="form-group col-md-4">
                <a href="{{ route('destination.index') }}" class="btn btn-flat btn-danger">Reset</a>
                <button class="btn btn-flat btn-primary">Search</button>
            </div>


        {!! Form::close() !!}
</div>
     <div class="table-responsive">
     
    <table class="table table-striped table-bordered table-hover">

        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Zawgyi Name</th>

                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
        @foreach($destinations as $row )
            <tr>

                <td class="counterCell"></td>
                <td>{{$row->name}}</td>
                <td>{{$row->translate('zg')['name']}}</td>
                <td>
                    <a href="{{ route('destination.edit', $row->id) }}" class="btn btn-warning btn-xs action-item" target="_blank"><i class="glyphicon glyphicon-edit"></i></a>
                </td>
                <td>
                    <form action="{{ route('destination.destroy',$row->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-xs ">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $destinations->links() }}
    </div>

    @endsection